"""Detection signals for Provenance Guard.

Signal 1 (LLM / Groq) is implemented in Milestone 3.
Signal 2 (stylometry) and the confidence scorer are added in Milestone 4.
"""

import json
import os
import re
import statistics

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

# Prompt asks the model to judge how likely the text is AI-generated and to
# return a strict JSON object so we get a machine-readable score, not prose.
_LLM_SYSTEM_PROMPT = """You are a forensic writing analyst for a creative-sharing \
platform. Given a piece of text, estimate the probability that it was generated by an \
AI language model rather than written by a human.

Weigh signals like: uniformity of tone, evenness of hedging, generic "assistant" phrasing, \
lack of lived-in specificity or idiosyncrasy, and overly balanced structure (these suggest \
AI). Weigh idiosyncratic voice, specific personal detail, irregular rhythm, and genuine \
messiness as human signals.

Respond with ONLY a JSON object of the form:
{"ai_probability": <float 0..1>, "rationale": "<one concise sentence>"}
where 1.0 means almost certainly AI-generated and 0.0 means almost certainly human."""


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, float(x)))


def llm_signal(text: str, client: Groq | None = None) -> dict:
    """Signal 1: ask Groq how likely `text` is AI-generated.

    Returns {"score": float in [0,1], "rationale": str}. Score 1.0 = confidently AI.
    On any API/parse failure returns a neutral 0.5 with an error rationale so the
    pipeline degrades gracefully rather than crashing.
    """
    client = client or Groq(api_key=os.environ["GROQ_API_KEY"])
    try:
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _LLM_SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        payload = json.loads(resp.choices[0].message.content)
        score = _clamp01(payload.get("ai_probability", 0.5))
        rationale = str(payload.get("rationale", "")).strip() or "(no rationale returned)"
        return {"score": score, "rationale": rationale}
    except Exception as exc:  # pragma: no cover - network/parse safety net
        return {"score": 0.5, "rationale": f"LLM signal unavailable: {exc}"}


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric heuristics (pure Python, Milestone 4)
# ---------------------------------------------------------------------------

# Punctuation marks that tend to appear more in idiosyncratic human writing.
_HUMAN_PUNCT = re.compile(r"[—–…();]|\.\.\.|\bi\b")

# Very short text has unstable statistics; below this we damp the signal toward
# 0.5 (uncertain) rather than trusting the raw numbers (edge case in planning.md).
_SHORT_TEXT_WORDS = 40


def _split_sentences(text: str) -> list[str]:
    parts = re.split(r"(?<=[.!?])\s+|\n+", text.strip())
    return [p for p in parts if p.strip()]


def _tokenize(text: str) -> list[str]:
    return re.findall(r"[a-zA-Z']+", text.lower())


def stylometry_signal(text: str) -> dict:
    """Signal 2: structural regularity of the text.

    Returns {"score": float in [0,1], "metrics": {...}}. Score 1.0 = maximally
    uniform / AI-like. Combines three sub-metrics, each mapped to an AI-likeness
    partial in [0,1]:
      - burstiness   : coefficient of variation of sentence lengths (low CV = AI)
      - ttr          : type-token ratio over a capped window (low diversity = AI/uniform)
      - punctuation  : density of human-signal punctuation (more = human)
    """
    words = _tokenize(text)
    sentences = _split_sentences(text)
    n_words = len(words)

    # Sub-metric 1: burstiness (coefficient of variation of sentence lengths).
    sent_lengths = [len(_tokenize(s)) for s in sentences]
    sent_lengths = [n for n in sent_lengths if n > 0]
    if len(sent_lengths) >= 2:
        mean_len = statistics.mean(sent_lengths)
        cv = statistics.pstdev(sent_lengths) / mean_len if mean_len else 0.0
    else:
        cv = 0.0
    # cv >= 0.6 is very human/bursty -> AI-likeness 0; cv 0 -> AI-likeness 1.
    burstiness_ai = 1.0 - _clamp01(cv / 0.6)

    # Sub-metric 2: type-token ratio over a capped window (reduces length bias).
    window = words[:200]
    ttr = len(set(window)) / len(window) if window else 0.0
    # Low diversity (<=0.35, heavy repetition/uniformity) reads AI; >=0.70 reads human.
    ttr_ai = 1.0 - _clamp01((ttr - 0.35) / 0.35)

    # Sub-metric 3: human-signal punctuation density (per 100 words).
    human_punct = len(_HUMAN_PUNCT.findall(text))
    punct_per_100 = (human_punct / n_words * 100) if n_words else 0.0
    # >= 4 such marks per 100 words is very human -> AI-likeness 0.
    punct_ai = 1.0 - _clamp01(punct_per_100 / 4.0)

    score = 0.5 * burstiness_ai + 0.2 * ttr_ai + 0.3 * punct_ai

    # Damp toward uncertainty for very short inputs (unstable statistics).
    if n_words < _SHORT_TEXT_WORDS:
        damp = n_words / _SHORT_TEXT_WORDS
        score = 0.5 + (score - 0.5) * damp

    return {
        "score": round(_clamp01(score), 4),
        "metrics": {
            "n_words": n_words,
            "n_sentences": len(sent_lengths),
            "cv_sentence_length": round(cv, 4),
            "ttr": round(ttr, 4),
            "human_punct_per_100w": round(punct_per_100, 4),
            "burstiness_ai": round(burstiness_ai, 4),
            "ttr_ai": round(ttr_ai, 4),
            "punct_ai": round(punct_ai, 4),
        },
    }


# ---------------------------------------------------------------------------
# Signal 3 — AI-phrase lexicon detector (pure Python, Stretch: ensemble) · lexical
# ---------------------------------------------------------------------------

# Phrases/words empirically over-represented in instruction-tuned LLM output. Multiword
# entries are stronger tells; single words are noisier (also used by humans) so they're
# weighted less below. All matched case-insensitively with word boundaries.
_AI_PHRASES = [
    "it is important to note", "it is worth noting", "it is essential to",
    "it is crucial to", "plays a crucial role", "play a crucial role",
    "plays a significant role", "navigate the complexities",
    "navigating the complexities", "a testament to", "in today's fast-paced world",
    "in today's world", "in the realm of", "in conclusion", "in summary",
    "when it comes to", "a wide range of", "at the end of the day",
    "paradigm shift", "unlock the potential", "the world of",
]
_AI_WORDS = [
    "furthermore", "moreover", "delve", "tapestry", "transformative", "seamless",
    "seamlessly", "multifaceted", "holistic", "robust", "comprehensive", "myriad",
    "leverage", "underscore", "underscores", "foster", "cutting-edge", "ever-evolving",
    "ever-changing", "notably", "essential", "crucial",
]

_PHRASE_RE = re.compile("|".join(re.escape(p) for p in _AI_PHRASES), re.IGNORECASE)
_WORD_RE = re.compile(r"\b(" + "|".join(re.escape(w) for w in _AI_WORDS) + r")\b", re.IGNORECASE)


def phrase_signal(text: str) -> dict:
    """Signal 3: density of characteristic AI boilerplate vocabulary.

    Returns {"score": float in [0,1], "metrics": {...}}. Score 1.0 = dense AI boilerplate.
    Multiword phrase hits count double (stronger tells); the weighted hit count is turned
    into a per-100-word density and capped at 3 (>=3 weighted hits/100w reads fully AI).
    """
    n_words = len(_tokenize(text))
    phrase_hits = len(_PHRASE_RE.findall(text))
    word_hits = len(_WORD_RE.findall(text))
    weighted = 2 * phrase_hits + 1 * word_hits
    density = (weighted / n_words * 100) if n_words else 0.0
    score = _clamp01(density / 3.0)

    if n_words < _SHORT_TEXT_WORDS:  # unstable on tiny inputs; damp toward 0.5
        score = 0.5 + (score - 0.5) * (n_words / _SHORT_TEXT_WORDS)

    return {
        "score": round(_clamp01(score), 4),
        "metrics": {
            "phrase_hits": phrase_hits,
            "word_hits": word_hits,
            "weighted_hits_per_100w": round(density, 4),
        },
    }


# ---------------------------------------------------------------------------
# Confidence scorer — combine the signals into one P(AI) (Milestone 4 + ensemble)
# ---------------------------------------------------------------------------

# Attribution band thresholds (asymmetric — biased against false positives).
AI_THRESHOLD = 0.70        # confidence >= this  -> likely_ai
HUMAN_THRESHOLD = 0.35     # confidence <= this  -> likely_human
DISAGREEMENT_K = 0.5       # how hard disagreement pulls toward 0.5

# Ensemble weights (weighted vote). LLM highest (semantic), phrase lowest (noisiest).
LLM_WEIGHT = 0.5
STYLE_WEIGHT = 0.3
PHRASE_WEIGHT = 0.2


def _attribution_for(confidence: float) -> str:
    if confidence >= AI_THRESHOLD:
        return "likely_ai"
    if confidence <= HUMAN_THRESHOLD:
        return "likely_human"
    return "uncertain"


def score_confidence(llm_score: float, style_score: float, phrase_score: float) -> dict:
    """Combine the three signals into a single confidence = P(AI) in [0,1] (ensemble).

        base         = 0.5*llm + 0.3*style + 0.2*phrase       # weighted vote
        disagreement = max(signals) - min(signals)            # spread across the 3
        confidence   = 0.5 + (base - 0.5) * (1 - 0.5*disagreement)

    Disagreement shrinkage pulls the score toward 0.5 when the signals conflict, so no
    lone confident signal can brand content on its own (false-positive protection). With
    three signals a single dissenter widens the spread and pulls toward 'uncertain'.
    """
    llm_score = _clamp01(llm_score)
    style_score = _clamp01(style_score)
    phrase_score = _clamp01(phrase_score)
    base = LLM_WEIGHT * llm_score + STYLE_WEIGHT * style_score + PHRASE_WEIGHT * phrase_score
    disagreement = max(llm_score, style_score, phrase_score) - min(llm_score, style_score, phrase_score)
    confidence = 0.5 + (base - 0.5) * (1 - DISAGREEMENT_K * disagreement)
    confidence = _clamp01(confidence)
    return {
        "confidence": round(confidence, 4),
        "attribution": _attribution_for(confidence),
        "disagreement": round(disagreement, 4),
    }


if __name__ == "__main__":
    # Quick manual test of Signal 1 in isolation (Milestone 3 verification).
    from dotenv import load_dotenv

    load_dotenv()
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, it "
            "is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? underwhelming. "
            "the broth was fine but they put WAY too much sodium in it and i was thirsty for "
            "like three hours after. probably won't go back unless someone drags me there"
        ),
    }
    for name, txt in samples.items():
        result = llm_signal(txt)
        print(f"{name:14s} score={result['score']:.2f}  :: {result['rationale']}")
