"""Detection signals for Provenance Guard.

Signal 1 (LLM / Groq) is implemented in Milestone 3.
Signal 2 (stylometry) and the confidence scorer are added in Milestone 4.
"""

import json
import os

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

# Prompt asks the model to judge how likely the text is AI-generated and to
# return a strict JSON object so we get a machine-readable score, not prose.
_LLM_SYSTEM_PROMPT = """You are a forensic writing analyst for a creative-sharing \
platform. Given a piece of text, estimate the probability that it was generated by an \
AI language model rather than written by a human.

Weigh signals like: uniformity of tone, evenness of hedging, generic "assistant" phrasing, \
lack of lived-in specificity or idiosyncrasy, and overly balanced structure (these suggest \
AI). Weigh idiosyncratic voice, specific personal detail, irregular rhythm, and genuine \
messiness as human signals.

Respond with ONLY a JSON object of the form:
{"ai_probability": <float 0..1>, "rationale": "<one concise sentence>"}
where 1.0 means almost certainly AI-generated and 0.0 means almost certainly human."""


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, float(x)))


def llm_signal(text: str, client: Groq | None = None) -> dict:
    """Signal 1: ask Groq how likely `text` is AI-generated.

    Returns {"score": float in [0,1], "rationale": str}. Score 1.0 = confidently AI.
    On any API/parse failure returns a neutral 0.5 with an error rationale so the
    pipeline degrades gracefully rather than crashing.
    """
    client = client or Groq(api_key=os.environ["GROQ_API_KEY"])
    try:
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _LLM_SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        payload = json.loads(resp.choices[0].message.content)
        score = _clamp01(payload.get("ai_probability", 0.5))
        rationale = str(payload.get("rationale", "")).strip() or "(no rationale returned)"
        return {"score": score, "rationale": rationale}
    except Exception as exc:  # pragma: no cover - network/parse safety net
        return {"score": 0.5, "rationale": f"LLM signal unavailable: {exc}"}


if __name__ == "__main__":
    # Quick manual test of Signal 1 in isolation (Milestone 3 verification).
    from dotenv import load_dotenv

    load_dotenv()
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, it "
            "is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? underwhelming. "
            "the broth was fine but they put WAY too much sodium in it and i was thirsty for "
            "like three hours after. probably won't go back unless someone drags me there"
        ),
    }
    for name, txt in samples.items():
        result = llm_signal(txt)
        print(f"{name:14s} score={result['score']:.2f}  :: {result['rationale']}")
